In [11]:
import pandas as pd
import numpy as np
import itertools as it

In [12]:
games = pd.read_csv('./data/games.csv')
GAME1 = games.iloc[0].gameId

In [13]:
plays = pd.read_csv('./data/plays.csv')
plays = plays[plays['gameId'] == GAME1]
PLAY1 = plays.iloc[0].playId

In [14]:
week1 = pd.read_csv('./data/week1.csv')
wgp1 = week1.loc[(week1['gameId'] == GAME1) & (week1['playId'] == PLAY1) & (week1['position'] != 'QB') & (week1['team'] != 'football')]
wgp1

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,2018090600,75,left,NaN
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,2018090600,75,left,HITCH
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,2018090600,75,left,NaN
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,2018090600,75,left,HITCH
5,2018-09-07T01:07:14.599Z,73.64,28.70,0.03,0.02,0.01,103.05,219.41,None,2534832.0,Rodney McLeod,23.0,FS,1,home,2018090600,75,left,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,2018-09-07T01:07:20.400Z,75.33,12.57,2.55,4.00,0.27,305.76,227.43,None,2552689.0,Ronald Darby,21.0,CB,59,home,2018090600,75,left,NaN
821,2018-09-07T01:07:20.400Z,76.75,52.42,3.86,3.56,0.39,55.22,22.42,None,2555383.0,Jalen Mills,31.0,CB,59,home,2018090600,75,left,NaN
822,2018-09-07T01:07:20.400Z,77.41,9.59,3.44,5.45,0.38,96.53,182.50,None,2555415.0,Austin Hooper,81.0,TE,59,away,2018090600,75,left,OUT
823,2018-09-07T01:07:20.400Z,78.06,38.54,5.47,3.04,0.56,336.15,338.39,None,2558175.0,Nate Gerry,47.0,LB,59,home,2018090600,75,left,NaN
824,2018-09-07T01:07:20.400Z,84.31,5.74,3.78,4.31,0.38,39.11,246.16,None,2559033.0,Ricky Ortiz,30.0,FB,59,away,2018090600,75,left,FLAT

In [15]:
pd.unique(wgp1.event)

array(['None', 'ball_snap', 'pass_forward', 'pass_arrived',
       'pass_outcome_caught', 'out_of_bounds'], dtype=object)

In [16]:
time1 = wgp1[wgp1['event'] == 'ball_snap'].time.iloc[0]
time2 = wgp1[wgp1['event'] == 'pass_forward'].time.iloc[0]
wgp1_tf = wgp1.loc[(wgp1['time'] >= time1) & (wgp1['time'] <= time2)]
wgp1_tf

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
141,2018-09-07T01:07:15.599Z,88.89,36.50,0.01,0.01,0.00,104.49,36.45,ball_snap,79848.0,Malcolm Jenkins,27.0,SS,11,home,2018090600,75,left,NaN
142,2018-09-07T01:07:15.599Z,91.36,44.14,0.00,0.01,0.02,289.53,49.86,ball_snap,2495454.0,Julio Jones,11.0,WR,11,away,2018090600,75,left,HITCH
143,2018-09-07T01:07:15.599Z,86.47,22.03,0.18,0.07,0.01,71.89,82.30,ball_snap,2495613.0,Corey Graham,24.0,FS,11,home,2018090600,75,left,NaN
144,2018-09-07T01:07:15.599Z,90.78,36.16,0.00,0.00,0.00,259.19,294.93,ball_snap,2533040.0,Mohamed Sanu,12.0,WR,11,away,2018090600,75,left,HITCH
145,2018-09-07T01:07:15.599Z,73.61,28.70,0.02,0.02,0.00,110.09,258.40,ball_snap,2534832.0,Rodney McLeod,23.0,FS,11,home,2018090600,75,left,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,2018-09-07T01:07:18.099Z,79.51,20.00,2.99,0.69,0.30,78.25,259.75,pass_forward,2552689.0,Ronald Darby,21.0,CB,36,home,2018090600,75,left,NaN
499,2018-09-07T01:07:18.099Z,76.53,44.93,4.68,2.18,0.47,182.14,277.48,pass_forward,2555383.0,Jalen Mills,31.0,CB,36,home,2018090600,75,left,NaN
500,2018-09-07T01:07:18.099Z,83.20,21.36,6.21,2.68,0.62,262.52,260.44,pass_forward,2555415.0,Austin Hooper,81.0,TE,36,away,2018090600,75,left,OUT
501,2018-09-07T01:07:18.099Z,83.06,25.98,4.08,3.73,0.40,42.57,303.26,pass_forward,2558175.0,Nate Gerry,47.0,LB,36,home,2018090600,75,left,NaN
502,2018-09-07T01:07:18.099Z,89.62,18.39,6.75,1.51,0.67,197.78,208.19,pass_forward,2559033.0,Ricky Ortiz,30.0,FB,36,away,2018090600,75,left,FLAT

In [17]:
ball_snap = wgp1_tf[wgp1_tf['event'] == 'ball_snap']
offense = []
defense = []
for i,r in ball_snap.iterrows():
    tup = (r.nflId, r.x, r.y)
    if r.team == 'away':
        offense.append(tup)
    else:
        defense.append(tup)
prod = list((it.product(offense, defense)))
distances = [(wr[0], cb[0], np.linalg.norm(np.subtract([wr[1], wr[2]], [cb[1], cb[2]]))) for wr, cb in prod]
distances = sorted(distances, key=lambda t: t[2])

In [18]:
pairs = []
while(len(pairs) < len(offense)):
    closest = distances[0]
    pairs.append(closest)
    distances = list(filter(lambda d: (d[0] != closest[0]) and (d[1] != closest[1]), distances[1:]))
pairs

[(2533040.0, 79848.0, 1.9203385118254552),
 (2555415.0, 2495613.0, 4.833352873523718),
 (2495454.0, 2555383.0, 7.472857552502922),
 (2559033.0, 2558175.0, 9.420132695456049),
 (2543583.0, 2552315.0, 12.460914894180126)]

In [19]:
players = pd.read_csv('./data/players.csv')
p1 = players[players['nflId'] == 2533040].iloc[0].displayName
def mapIdsToName(tup):
    p1 = players[players['nflId'] == tup[0]].iloc[0].displayName
    p2 = players[players['nflId'] == tup[1]].iloc[0].displayName
    return (p1, p2)

In [20]:
list(map(mapIdsToName, pairs))

[('Mohamed Sanu', 'Malcolm Jenkins'),
 ('Austin Hooper', 'Corey Graham'),
 ('Julio Jones', 'Jalen Mills'),
 ('Ricky Ortiz', 'Nate Gerry'),
 ('Devonta Freeman', 'Jordan Hicks')]

In [39]:
PAIR1 = pairs[0]
times = pd.unique(wgp1_tf.time)
distance = []
for t in times:
    frame = wgp1_tf[wgp1_tf['time'] == t]
    receiver = frame[frame['nflId'] == PAIR1[0]]
    defender = frame[frame['nflId'] == PAIR1[1]]
    xdif = np.abs(receiver.x.values[0] - defender.x.values[0])
    ydif = np.abs(receiver.y.values[0] - defender.y.values[0])
    distances.append(np.linalg.norm((xdif, ydif)))

[1.9203385118254552,
 1.922134230484438,
 1.9123022773609784,
 1.908743041899559,
 1.889047378971739,
 1.8595160660774075,
 1.7925400971805387,
 1.6985876486069207,
 1.6033090781256103,
 1.4800675660252787,
 1.3708391590554947,
 1.2605157674539433,
 1.183427226321924,
 1.1543396380615163,
 1.2146192819151231,
 1.3336416310238692,
 1.500133327407934,
 1.7029973576021749,
 1.9405411616350734,
 2.1947665023869822,
 2.4884533349050395,
 2.7840976994351325,
 3.1260358283295453,
 3.4982424158425585,
 3.9036009017316236,
 4.349919539485749]